### ISSUE TITLE
crawl

### ISSUE THREAD

**Issue by GanghyeonSeo** [gsainfoteam/ziggle-be#65]

**Comment by siwonpada** [comment]
이거 test코드 만들 때, test 폴더 안에 해당 이름의 폴더를 만들고 그 안에서 테스트 코드를 만들어 주실 수 있나요.

**Comment by siwonpada** [comment]
돌아가는 코드와 테스트 코드가 같이 있으면 나중에 보기 조금 힘들 수 있을 것 같아서요.

**Comment by GanghyeonSeo** [comment]
test 폴더로 옮겼고 package.json에 있는 rootDir 수정했습니다. 여기서 작업 진행할게요.
