### ISSUE TITLE
[FEATURE] health check api 만들기

### ISSUE THREAD

**Issue by siwonpada** [gsainfoteam/ziggle-be#70]
### Description

health check api를 만들어서 서비스의 안정성을 더 높여야 한다.

### Todos

- [ ] redis, prisma, memory, http, disk 관련 health check api 만들기
- [ ] test code 만들기 (그냥 되는지만 확인하기)

### ETC

이를 이용해서 kube container 도 바꿀 수 있으면 좋을 것 같다.

**Comment by chungjung-d** [comment]
@siwonpada redis, prisma, memory, http, disk 등 health check api를 만든다고 했는데, metrics data를 수집하는 api를 만든다는 의미인가요

**Comment by siwonpada** [comment]
https://api.groups.gistory.me/health
와 같이 해당 서비스와 연관된 다른 서비스들이 잘 돌아가는지 확인하기 위한 용도입니다.

**Comment by chungjung-d** [comment]
health check api 쿠버에서 인식을 하는 포멧인건가요 아님 일단 api로만 제공을 하는건가요??

**Comment by siwonpada** [comment]
일단 api로만 제공하는 것입니다.
하지만, 쿠버 인식용으로 사용해도 될 것 같습니다.

**Comment by siwonpada** [comment]
일단 groups에 실험적으로 쿠버에 인식을 시켜놔봤는데 잘 작동하네요. 쿠버의 health check용으로 쓰면 될 듯 합니다.

@chungjung-d
