### ISSUE TITLE
[FEATURE] restrict title length

### ISSUE THREAD

**Issue by siwonpada** [gsainfoteam/ziggle-be#85]
### Description

제목에 최대 길이가 없어서 모든 내용을 제목에 넣을 수 있다. 이는 Fe UI에 문제가 생길 수 있다. 따라서 제목에 최대길이를 제한해야한다.

### Todos

- [ ] DTO 수정

### ETC

굳이 데이터 베이스를 건들일 필요는 없을 것 같다. 하지만, title이 사용되는 모든 dto에 제한을 걸어두어야 한다.

**Comment by controlZ** [comment]
지금 있는 제목중 가장 긴 타이틀(1000자 짜리 타이틀 제외) + 50자
